  server:
    port: 8080

  spring:
    application:
      name: transaction-processor
    datasource:
      url: postgresql://localhost:5432/mpesa
      driverClassName: org.postgresql.Driver
      username: sa
      password: ""
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: create-drop
    h2:
      console:
        enabled: true

  llm:
    api:
      url: "https://api.anthropic.com/v1/messages"
      key: "${ANTHROPIC_API_KEY:your-api-key-here}"
      model: "claude-3-sonnet-20240229"
      max-tokens: 4000

  logging:
    level:
      com.mpesa: DEBUG
      org.springframework.web: DEBUG